apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-2pwl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-2pwl
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-2pwl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-2pwl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-2pwl
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-tenant/appstudio/dc-metro-map-2pwl@sha256:48988b752687a614da500319d76a2d22392fac42bb04fd44c7f3731dc20b6c6d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
