apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-2pwl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-tenant/appstudio/dc-metro-map-2pwl@sha256:48988b752687a614da500319d76a2d22392fac42bb04fd44c7f3731dc20b6c6d
        name: my-nodejs
        resources: {}
status: {}
